### ISSUE TITLE
unexpected nil window in _UIApplicationHandleEventFromQueueEvent

### ISSUE THREAD

**Issue by DamonFish** [zhangxiaoshan618/iOSPlayerVerticalAndHorizontalScreenDemo#10]
iOS8.1 Simulator
warning "unexpected nil window in _UIApplicationHandleEventFromQueueEvent,"

"window = UIWindow()"
->
window = UIWindow.init(frame: UIScreen.main.bounds)

**Comment by zhangxiaoshan618** [comment]
这个问题我也很纠结，因为我之前也设置过window的frame。但是在实际工作中偶尔会遇到，设置window的frame有时候会导致有些时候在横竖屏切换时取 [UIScreen mainScreen]的宽高会出错。
在我们的应用中，使用UIWindow()设置window暂时还未发现问题。而且目前来说，iOS8的市场占有率已经可以忽略了。所以对于具体应该使用哪种方式设置window，我持谨慎态度。
