### ISSUE TITLE
可以直接在dismiss的转场中指定toView的frame = containerView的frame

### ISSUE THREAD

**Issue by icofans** [zhangxiaoshan618/iOSPlayerVerticalAndHorizontalScreenDemo#3]
可以直接在dismiss的转场中指定toView的frame = containerView的frame

**Comment by zhangxiaoshan618** [comment]
不可以啊，因为containerView是横屏的，toView是竖屏的，肯定不相等。如果你是想解决自定义转场动画中，横屏回到竖屏，竖屏的fram发生错误的问题，我记得我尝试过在dismiss的转场中强制设置正确的toView的frame,但是没效果，所以才设置到viewWillAppear中的。

**Comment by leverTsui** [comment]
在viewWillAppear中设置，真机调试是无效的 @zhangxiaoshan618
