### ISSUE TITLE
关于`FirstSmallController`的问题

### ISSUE THREAD

**Issue by zhouwk** [zhangxiaoshan618/iOSPlayerVerticalAndHorizontalScreenDemo#8]
感觉播放器控件先做UI动画处理，再无动画模态到另一个横屏的页面是一个很好的idea，用户体验也比较好一些，所以也想尝试一下。
我尝试设置

     playView.isHidden = true 
     contentView.backgroundColor = UIColor.orange

以此来观察你是如何处理设备旋转之后`contentView`做大小，位置，旋转逻辑处理的，结果发现这些逻辑执行结束之后，打印`contentView.frame`是`(-2.8421709430404e-14, 0.0, 375.0, 667.0)`(基于6s),而不是`CGRect(x: 0, y: 0, width: UIScreen.main.bounds.height, height: UIScreen.main.bounds.width)`, 可查看截图附件。

![2017-09-07 4 38 35](https://user-images.githubusercontent.com/29529512/30156962-a1ee55b8-93f3-11e7-965b-c0e5f87bd36d.png)
![2017-09-07 4 40 20](https://user-images.githubusercontent.com/29529512/30156965-a282a51a-93f3-11e7-89a9-9cd244d32bfb.png)
<hr/>

所以我感觉在设备旋转之后，你对`contentView`所做的如下操作似乎是错误的或者说没有带来正确的结果，但是`playerView`的展示是正确的，应该是对`playerView`进行约束布局的原因

      self?.contentView.bounds = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.height, height:  )
             self?.contentView.center = self!.view.center
            
            if controller is FirstLandscapeLeftController {
                self?.contentView.transform = CGAffineTransform(rotationAngle: CGFloat(-Double.pi / 2))
            }else {
                self?.contentView.transform = CGAffineTransform(rotationAngle: CGFloat(Double.pi / 2))
            }

<hr/>

还是我遗漏了什么细节处理，如果是这样的话，可以交流一下吗`QQ:2963329733`

**Comment by zhangxiaoshan618** [comment]
@neverstoplearn 这个情况我也遇到了，在我的第二种方法中提到了这个问题（详情请看README）。这应该属于系统的一个bug，但是这个bug在自定义转场动画会有实际影响（对使用第二种即自定义转场动画的方式有影响），在使用系统的转场时不会有影响（对第一种方式无影响）。所以我在第一种方法中并未考虑这个问题。在第二种方法中对这个问题进行了处理。
